# Generated by Django 4.2.9 on 2024-02-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='images_of_albums')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artiste', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('Music', 'Music'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Relax', 'Relax')], default='Music', max_length=20)),
                ('time_length', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('music', models.FileField(upload_to='musics')),
                ('image', models.ImageField(upload_to='images_of_musics')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musics.album')),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Musics',
                'db_table': 'music',
                'ordering': ('id',),
            },
        ),
    ]
