# Generated by Django 4.2.9 on 2024-02-03 22:17

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_alter_music_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images_of_genres')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=[('#FFFFFF', 'white'), ('#000000', 'black')])),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genre',
            },
        ),
        migrations.AlterField(
            model_name='music',
            name='artiste',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musics.genre'),
        ),
    ]
